version: "3.8"

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.email=${ACME_EMAIL:-contact@nayari.ai}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--api.dashboard=true"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "letsencrypt:/letsencrypt"
    networks:
      - web
    labels:
      - "traefik.enable=true"
      # Dashboard configuration
      - "traefik.http.routers.dashboard.rule=Host(`${TRAEFIK_DASHBOARD_HOST:-dashboard.localhost}`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.tls.certresolver=letsencrypt"
      # Basic auth for dashboard
      - "traefik.http.routers.dashboard.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=${TRAEFIK_DASHBOARD_AUTH:-admin:$$apr1$$xyz123...}"
    restart: unless-stopped

  tee:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eliza
    stdin_open: true
    tty: true
    volumes:
      - /var/run/tappd.sock:/var/run/tappd.sock
      - tee:/app/packages/client-twitter/src/tweetcache
      - tee:/app/db.sqlite
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.eliza.rule=Host(`${DOMAIN:-localhost}`)"
      - "traefik.http.routers.eliza.entrypoints=websecure"
      - "traefik.http.routers.eliza.tls.certresolver=letsencrypt"
      - "traefik.http.services.eliza.loadbalancer.server.port=3000"
    environment:
      # API Keys
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - REDPILL_API_KEY=${REDPILL_API_KEY}
      - ELEVENLABS_XI_API_KEY=${ELEVENLABS_XI_API_KEY}

      # ElevenLabs Configuration
      - ELEVENLABS_MODEL_ID=${ELEVENLABS_MODEL_ID:-eleven_multilingual_v2}
      - ELEVENLABS_VOICE_ID=${ELEVENLABS_VOICE_ID:-21m00Tcm4TlvDq8ikWAM}
      - ELEVENLABS_VOICE_STABILITY=${ELEVENLABS_VOICE_STABILITY:-0.5}
      - ELEVENLABS_VOICE_SIMILARITY_BOOST=${ELEVENLABS_VOICE_SIMILARITY_BOOST:-0.9}
      - ELEVENLABS_VOICE_STYLE=${ELEVENLABS_VOICE_STYLE:-0.66}
      - ELEVENLABS_VOICE_USE_SPEAKER_BOOST=${ELEVENLABS_VOICE_USE_SPEAKER_BOOST:-false}
      - ELEVENLABS_OPTIMIZE_STREAMING_LATENCY=${ELEVENLABS_OPTIMIZE_STREAMING_LATENCY:-4}
      - ELEVENLABS_OUTPUT_FORMAT=${ELEVENLABS_OUTPUT_FORMAT:-pcm_16000}

      # Twitter Configuration
      - TWITTER_DRY_RUN=${TWITTER_DRY_RUN:-false}
      - TWITTER_USERNAME=${TWITTER_USERNAME}
      - TWITTER_PASSWORD=${TWITTER_PASSWORD}
      - TWITTER_EMAIL=${TWITTER_EMAIL}

      # Blockchain and API Configuration
      - BIRDEYE_API_KEY=${BIRDEYE_API_KEY}
      - SOL_ADDRESS=${SOL_ADDRESS:-So11111111111111111111111111111111111111112}
      - SLIPPAGE=${SLIPPAGE:-1}
      - SOLANA_RPC_URL=${SOLANA_RPC_URL:-https://api.mainnet-beta.solana.com}
      - HELIUS_API_KEY=${HELIUS_API_KEY}

      # Server Configuration
      - SERVER_PORT=${SERVER_PORT:-3000}
      - WALLET_SECRET_SALT=${WALLET_SECRET_SALT}
    restart: unless-stopped

networks:
  web:
    name: web
    driver: bridge

volumes:
  letsencrypt:
    name: letsencrypt
  tee:
    name: tee